name: Reusable Maven Build Workflow

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      artifact-name:
        required: true
        type: string     
      artifact-path:
        required: true
        type: string  
jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: '${{ inputs.java-version }}'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --no-transfer-progress --file pom.xml       

    - name: Copy Jar or War files
      run: |
        for file in $(find target -type f \( -name "*.jar" -o -name "*.war" \))
        do
           mv $file ${{ inputs.artifact-path }}
        done

    - name: Upload the artifact 
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}
